### PR TITLE
Revert "added tree-sitter support"

### PR DESCRIPTION
**Pull request by bakageddy**
Reverts FrenzyExists/aquarium-vim#7

Hey, I just checked this with a bunch of file-types I didn't before, and frankly this pr makes the color-scheme look very monotonous. I apologize for this inconvenience and I will patch it as soon as I can before tomorrow. Sorry :(

### CODE REVIEW

**Comment by bakageddy** [comment]
I don't think this is how you intended this colorscheme to be after tree-sitter, please send some feedback so I can change it accordingly! Again sorry :disappointed: .

**Comment by FrenzyExists** [comment]
The line thingy on the middle, is that a vert-split?

**Comment by FrenzyExists** [comment]
I'll give a look later, since tomorrow I have exam

**Comment by bakageddy** [comment]
> The line thingy on the middle, is that a vert-split?

That's just a color column.
BTW all the best for your exam. This can be reviewed later.

**Pull request closed without merging**
